spring.application.name=backendcodebase
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/Career_Pilot?createDatabaseIfNotExist=true

spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.output.ansi.enabled=ALWAYS
# Format the SQL with indentation and line breaks instead of a single line
spring.jpa.properties.hibernate.format_sql=true
# Add comments explaining why the query was generated (e.g., criteria, HQL)
spring.jpa.properties.hibernate.use_sql_comments=true